replicaCount: 1

service:
  type: LoadBalancer

# Use this as a hosts file to set custom DNS records
customRecords: []

# The lists must be the same format as a hosts file
blockListUrls:
  - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

emptyDir:
  size: 100M

resources:
  coredns:
    limits:
      cpu: 100m
      memory: 120Mi
    requests:
      cpu: 100m
      memory: 120Mi
  blacklistRunner:
    limits:
      cpu: 10m
      memory: 20Mi
    requests:
      cpu: 10m
      memory: 20Mi

autoscaling:
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 65