apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  Corefile: |
    . {
        hosts /etc/blacklist/hosts {
            {{- if .Values.customRecords }}
              {{- .Values.customRecords | join "\n" | nindent 12 -}}
            {{ end }}
            no_reverse
            reload 12h
            fallthrough
        }
        forward . 8.8.8.8 9.9.9.9
        reload
        cache
        health
        errors
    }
